name: Lint Python Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pylint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint

    - name: Setup PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:$(pwd)

    - name: Run Pylint
      run: |
        echo "Linting Python files..."
        pylint **/*.py || exit 1

    - name: Verify Python Version
      run: python --version

    - name: Debug Python Version from Matrix
      run: |
        echo "Specified Python version: ${{ matrix.python-version }}"
