name: Lint with Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Add Required Repositories
      - name: Add Python PPA
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update

      # Step 3: Install Python 3.10 and Related Tools
      - name: Install Python 3.10
        run: |
          sudo apt-get install -y python3.10 python3.10-venv python3.10-distutils
          python3.10 --version  # Verify installation
   
      # Step 3.5 - specify what version is known now....
      - name: Debug Python Version
        run: |
          echo "Specified Python version: ${{ matrix.python-version }}"

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      # Step 6: Run Pylint on the codebase
      - name: Run Pylint
        run: |
          source venv/bin/activate
          pylint --rcfile=.pylintrc $(find . -name "*.py")